# go_emotions Dataset

In [ ]:
from datasets import load_dataset

ds = load_dataset("google-research-datasets/go_emotions", "raw")

README.md: 0.00B [00:00, ?B/s]

raw/train-00000-of-00001.parquet:   0%|          | 0.00/24.8M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/211225 [00:00<?, ? examples/s]

In [ ]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'id', 'author', 'subreddit', 'link_id', 'parent_id', 'created_utc', 'rater_id', 'example_very_unclear', 'admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral'],
        num_rows: 211225
    })
})

In [ ]:
ds['train']

Dataset({
    features: ['text', 'id', 'author', 'subreddit', 'link_id', 'parent_id', 'created_utc', 'rater_id', 'example_very_unclear', 'admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral'],
    num_rows: 211225
})

In [ ]:
import pandas as pd
df = ds['train'].to_pandas()
display(df.head())

,text,id,author,subreddit,link_id,parent_id,created_utc,rater_id,example_very_unclear,admiration,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,eew5j0j,Brdd9,nrl,t3_ajis4z,t1_eew18eq,1.548381e+09,1,False,0,...,0,0,0,0,0,0,0,1,0,0
1,>sexuality shouldn’t be a grouping category I...,eemcysk,TheGreen888,unpopularopinion,t3_ai4q37,t3_ai4q37,1.548084e+09,37,False,0,...,0,0,0,0,0,0,0,0,0,0
2,"You do right, if you don't care then fuck 'em!",ed2mah1,Labalool,confessions,t3_abru74,t1_ed2m7g7,1.546428e+09,37,False,0,...,0,0,0,0,0,0,0,0,0,1
3,Man I love reddit.,eeibobj,MrsRobertshaw,facepalm,t3_ahulml,t3_ahulml,1.547965e+09,18,False,0,...,1,0,0,0,0,0,0,0,0,0
4,"[NAME] was nowhere near them, he was by the Fa...",eda6yn6,American_Fascist713,starwarsspeculation,t3_ackt2f,t1_eda65q2,1.546669e+09,2,False,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
df_copy = df.copy()

In [ ]:
df_copy.drop(['id'	,'author'	,'subreddit'	,'link_id'	,'parent_id'	,'created_utc'	,'rater_id',	'example_very_unclear'],axis=1,inplace=True)

In [ ]:
df_copy.head()

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,>sexuality shouldn’t be a grouping category I...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,"You do right, if you don't care then fuck 'em!",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,Man I love reddit.,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,"[NAME] was nowhere near them, he was by the Fa...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
# Identify emotion columns (only numeric columns, excluding 'text' and other metadata)
emotion_columns = df_copy.select_dtypes(include=['number']).columns

# Calculate the sum of emotion scores for each row
df_copy['total_emotion_score'] = df_copy[emotion_columns].sum(axis=1)

# Filter rows where the total emotion score is 0
rows_without_emotion = df_copy[df_copy['total_emotion_score'] == 0]

# Display the head of the filtered DataFrame
display(rows_without_emotion.head())

Empty DataFrame
Columns: [text, admiration, amusement, anger, annoyance, approval, caring, confusion, curiosity, desire, disappointment, disapproval, disgust, embarrassment, excitement, fear, gratitude, grief, joy, love, nervousness, optimism, pride, realization, relief, remorse, sadness, surprise, neutral, total_emotion_score]
Index: []

[0 rows x 30 columns]

In [ ]:
len(rows_without_emotion)

3411

In [ ]:
len(df_copy[df_copy['total_emotion_score'] > 1])

35994

In [ ]:
# Remove rows where no emotion is present (total_emotion_score == 0)
df_copy = df_copy[df_copy['total_emotion_score'] > 0]

# Drop the temporary 'total_emotion_score' column
df_copy.drop(columns=['total_emotion_score'], inplace=True)

# Display the head of the modified DataFrame
display(df_copy.head())

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,"You do right, if you don't care then fuck 'em!",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,Man I love reddit.,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,"[NAME] was nowhere near them, he was by the Fa...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,Right? Considering it’s such an important docu...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_copy.shape

(207814, 29)

In [ ]:
cols = df_copy.columns.values
cols = cols[cols != 'text']

In [ ]:
cols

array(['admiration', 'amusement', 'anger', 'annoyance', 'approval',
       'caring', 'confusion', 'curiosity', 'desire', 'disappointment',
       'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear',
       'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism',
       'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise',
       'neutral'], dtype=object)

In [ ]:
df_copy.duplicated().sum()

np.int64(56410)

In [ ]:
df_copy.drop_duplicates()

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,"You do right, if you don't care then fuck 'em!",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,Man I love reddit.,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,"[NAME] was nowhere near them, he was by the Fa...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,Right? Considering it’s such an important docu...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211216,Tell her youre sleeping with someone else. You...,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
211217,You got banned for participating in a brigade.,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
211219,"Well, I'm glad you're out of all that now. How...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
211221,Well when you’ve imported about a gazillion of...,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
211223,The FDA has plenty to criticize. But like here...,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
import numpy as np

# Get all unique duplicated texts
duplicated_texts = df_copy[df_copy['text'].duplicated(keep=False)]['text'].unique()

if len(duplicated_texts) > 0:
    # Randomly select one of the duplicated texts
    random_duplicated_text = np.random.choice(duplicated_texts)

    print(f"Randomly selected duplicated text: '{random_duplicated_text}'")

    # Filter the original DataFrame to show all occurrences of this specific text
    all_occurrences_of_random_text = df_copy[df_copy['text'] == random_duplicated_text]

    print(f"Displaying all {len(all_occurrences_of_random_text)} occurrences of '{random_duplicated_text}':")

    # Use option_context to display all columns and rows without truncation
    with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.expand_frame_repr', False):
        display(all_occurrences_of_random_text.sort_values(by='text'))
else:
    print("No duplicated texts found in the DataFrame.")

No duplicated texts found in the DataFrame.

In [ ]:
df_copy.columns

Index(['text', 'admiration', 'amusement', 'anger', 'annoyance', 'approval',
       'caring', 'confusion', 'curiosity', 'desire', 'disappointment',
       'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear',
       'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride',
       'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral'],
      dtype='object')

In [ ]:
emotion_cols = [
    'admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring',
    'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval',
    'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief',
    'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization',
    'relief', 'remorse', 'sadness', 'surprise', 'neutral'
]

# Ensure labels are numeric (in case they are strings)
df_copy[emotion_cols] = df_copy[emotion_cols].astype(int)

# Group by text and aggregate
df_copy = df_copy.groupby("text", as_index=False)[emotion_cols].max()

In [ ]:
import numpy as np

# Get all unique duplicated texts
duplicated_texts = df_copy[df_copy['text'].duplicated(keep=False)]['text'].unique()

if len(duplicated_texts) > 0:
    # Randomly select one of the duplicated texts
    random_duplicated_text = np.random.choice(duplicated_texts)

    print(f"Randomly selected duplicated text: '{random_duplicated_text}'")

    # Filter the original DataFrame to show all occurrences of this specific text
    all_occurrences_of_random_text = df_copy[df_copy['text'] == random_duplicated_text]

    print(f"Displaying all {len(all_occurrences_of_random_text)} occurrences of '{random_duplicated_text}':")

    # Use option_context to display all columns and rows without truncation
    with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.expand_frame_repr', False):
        display(all_occurrences_of_random_text.sort_values(by='text'))
else:
    print("No duplicated texts found in the DataFrame.")

No duplicated texts found in the DataFrame.

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df_copy[df_copy['text'] == 'I wonder what was stopping that barber using the lightning network for payments?']

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,disappointment,disapproval,disgust,embarrassment,excitement,fear,gratitude,grief,joy,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
20276,I wonder what was stopping that barber using t...,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [ ]:
df_copy.shape

(57730, 29)

In [ ]:
display(df_copy.sample(n=4))

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,disappointment,disapproval,disgust,embarrassment,excitement,fear,gratitude,grief,joy,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
10370,Good luck for everyone pronouncing [NAME] name...,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0
47090,What the fuck are you talking about,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35097,She eats it until she throws up the first snow...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
9503,"Four score and seven years ago, we and a jewel...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

# emotion Dataset

In [ ]:
from datasets import load_dataset

ds = load_dataset("dair-ai/emotion", "unsplit")

README.md: 0.00B [00:00, ?B/s]

unsplit/train-00000-of-00001.parquet:   0%|          | 0.00/26.9M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/416809 [00:00<?, ? examples/s]

In [ ]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 416809
    })
})

In [ ]:
df_2 = ds['train'].to_pandas()
df_2.head()

                                                text  label
0  i feel awful about it too because it s my job ...      0
1                              im alone i feel awful      0
2  ive probably mentioned this before but i reall...      1
3           i was feeling a little low few days back      0
4  i beleive that i am much more sensitive to oth...      2

In [ ]:
df_2.shape

(416809, 2)

In [ ]:
df_2.duplicated().sum()

np.int64(686)

In [ ]:
df_2['text'].duplicated().sum()

np.int64(22987)

In [ ]:
# df_3.drop_duplicates(subset=['text'], inplace=True)

In [ ]:
emotion_mapping = {
    'sadness': 0,
    'joy': 1,
    'love': 2,
    'anger': 3,
    'fear': 4,
    'surprise': 5
}

print("Emotion mapping dictionary:")
print(emotion_mapping)

Emotion mapping dictionary:
{'sadness': 0, 'joy': 1, 'love': 2, 'anger': 3, 'fear': 4, 'surprise': 5}

In [ ]:
# Create a reverse mapping dictionary
reverse_emotion_mapping = {v: k for k, v in emotion_mapping.items()}

# Map the numeric labels in df_2 to their corresponding emotion names
df_2['label_text'] = df_2['label'].map(reverse_emotion_mapping)

# Display the results
print("Reverse mapping:", reverse_emotion_mapping)
display(df_2.head())

Reverse mapping: {0: 'sadness', 1: 'joy', 2: 'love', 3: 'anger', 4: 'fear', 5: 'surprise'}

                                                text  label label_text
0  i feel awful about it too because it s my job ...      0    sadness
1                              im alone i feel awful      0    sadness
2  ive probably mentioned this before but i reall...      1        joy
3           i was feeling a little low few days back      0    sadness
4  i beleive that i am much more sensitive to oth...      2       love

In [ ]:
import numpy as np

# Get all unique duplicated texts
duplicated_texts = df_2[df_2['text'].duplicated(keep=False)]['text'].unique()

if len(duplicated_texts) > 0:
    # Randomly select one of the duplicated texts
    random_duplicated_text = np.random.choice(duplicated_texts)

    print(f"Randomly selected duplicated text: '{random_duplicated_text}'")

    # Filter the original DataFrame to show all occurrences of this specific text
    all_occurrences_of_random_text = df_2[df_2['text'] == random_duplicated_text]

    print(f"Displaying all {len(all_occurrences_of_random_text)} occurrences of '{random_duplicated_text}':")

    # Use option_context to display all columns and rows without truncation
    with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.expand_frame_repr', False):
        display(all_occurrences_of_random_text.sort_values(by='text'))
else:
    print("No duplicated texts found in the DataFrame.")

Randomly selected duplicated text: 'i feel is worth supporting'
Displaying all 2 occurrences of 'i feel is worth supporting':

                              text  label label_text
232091  i feel is worth supporting      1        joy
304942  i feel is worth supporting      2       love

In [ ]:
# Perform one-hot encoding on the 'label_text' column
df_3_encoded = pd.get_dummies(df_2, columns=['label_text'], prefix='', prefix_sep='')

# Display the first few rows to verify
display(df_3_encoded.head())

,text,label,anger,fear,joy,love,sadness,surprise
0,i feel awful about it too because it s my job ...,0,False,False,False,False,True,False
1,im alone i feel awful,0,False,False,False,False,True,False
2,ive probably mentioned this before but i reall...,1,False,False,True,False,False,False
3,i was feeling a little low few days back,0,False,False,False,False,True,False
4,i beleive that i am much more sensitive to oth...,2,False,False,False,True,False,False

In [ ]:
emotion_cols = ['anger', 'fear', 'joy', 'love', 'sadness', 'surprise']

# Use the encoded dataframe where these columns actually exist
# Convert boolean values to integers (0 and 1)
df_3_encoded[emotion_cols] = df_3_encoded[emotion_cols].astype(int)

# Group by text and aggregate to handle duplicate rows for the same text
df_3_final = df_3_encoded.groupby("text", as_index=False)[emotion_cols].max()

print(f"Final shape after grouping: {df_3_final.shape}")
display(df_3_final.head())

Final shape after grouping: (393822, 7)

,text,anger,fear,joy,love,sadness,surprise
0,a a documentary in which baby fur seals were b...,0,0,0,0,1,0
1,a and i were walking along the new asia stairw...,0,0,0,0,1,0
2,a bad smelling cucumber,1,0,0,0,0,0
3,a boy i had been admiring so much asked me to ...,0,0,1,0,0,0
4,a boy i look after for the probation service d...,0,0,0,0,1,0

In [ ]:
df_3 = df_3_final

In [ ]:
df_3.head()

,text,anger,fear,joy,love,sadness,surprise
0,a a documentary in which baby fur seals were b...,0,0,0,0,1,0
1,a and i were walking along the new asia stairw...,0,0,0,0,1,0
2,a bad smelling cucumber,1,0,0,0,0,0
3,a boy i had been admiring so much asked me to ...,0,0,1,0,0,0
4,a boy i look after for the probation service d...,0,0,0,0,1,0

# Merging

In [ ]:
df_copy.head()

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,disappointment,disapproval,disgust,embarrassment,excitement,fear,gratitude,grief,joy,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,"""If you don't wear BROWN AND ORANGE...YOU DON...",0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
1,"""What do Scottish people look like?"" How I wo...",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,"### A surprise, to be sure, but a welcome one",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,"'*Pray*, v. To ask that the laws of the unive...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,">it'll get invaded by tankie, unfortunately. ...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [ ]:
print(df_3.shape)
print(df_copy.shape)

(393822, 7)
(57730, 29)

In [ ]:
# Stack df_copy and df_3 vertically
df_stacked = pd.concat([df_copy, df_3], axis=0, ignore_index=True)

# Fill NaN values with 0 for columns that didn't exist in one of the dataframes
df_stacked = df_stacked.fillna(0)

print(f"Stacked DataFrame shape: {df_stacked.shape}")
display(df_stacked.head())
display(df_stacked.tail())

Stacked DataFrame shape: (451552, 29)

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,disappointment,disapproval,disgust,embarrassment,excitement,fear,gratitude,grief,joy,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,"""If you don't wear BROWN AND ORANGE...YOU DON...",0.0,0.0,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0,0,1.0
1,"""What do Scottish people look like?"" How I wo...",0.0,0.0,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0
2,"### A surprise, to be sure, but a welcome one",0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0
3,"'*Pray*, v. To ask that the laws of the unive...",0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1.0
4,">it'll get invaded by tankie, unfortunately. ...",0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1.0

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,disappointment,disapproval,disgust,embarrassment,excitement,fear,gratitude,grief,joy,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
451547,yesterday when i received a b on a history mid...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0
451548,you ignored the fact that we could not hear yo...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0.0
451549,you may find out that i am stupid and not to l...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0
451550,you told me psychology can help people to be h...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0
451551,your prejudice against psychology students and...,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0

In [ ]:
print(df_stacked.shape)
print(df_3.shape)
print(df_copy.shape)

(451552, 29)
(393822, 7)
(57730, 29)

In [ ]:
df_stacked.duplicated().sum()

np.int64(0)

In [ ]:
import numpy as np

# Get all unique duplicated texts
duplicated_texts = df_stacked[df_stacked['text'].duplicated(keep=False)]['text'].unique()

if len(duplicated_texts) > 0:
    # Randomly select one of the duplicated texts
    random_duplicated_text = np.random.choice(duplicated_texts)

    print(f"Randomly selected duplicated text: '{random_duplicated_text}'")

    # Filter the original DataFrame to show all occurrences of this specific text
    all_occurrences_of_random_text = df_stacked[df_stacked['text'] == random_duplicated_text]

    print(f"Displaying all {len(all_occurrences_of_random_text)} occurrences of '{random_duplicated_text}':")

    # Use option_context to display all columns and rows without truncation
    with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.expand_frame_repr', False):
        display(all_occurrences_of_random_text.sort_values(by='text'))
else:
    print("No duplicated texts found in the DataFrame.")

No duplicated texts found in the DataFrame.

In [ ]:
# Return a random row from the stacked dataframe
display(df_stacked.sample(n=4))

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,disappointment,disapproval,disgust,embarrassment,excitement,fear,gratitude,grief,joy,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
307680,i know is we woke up feeling loving,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0
294580,i honestly do not feel that distressed,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0
319995,i loved her and went out of my way make her fe...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0
217617,i feel relaxed and with no stress because its ...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0

In [ ]:
import re
import numpy as np

# Define cleaning patterns in a dictionary
cleaning_patterns = {
    'URL': r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+|www\\.[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}',
    'HTML Tags': r'<[^>]*>',
    'Extra Whitespace': r'\s+',
    'Special Characters': r'[^a-zA-Z0-9\s]'
}

print("Pattern Analysis:")
for name, pattern in cleaning_patterns.items():
    has_pattern = df_stacked['text'].str.contains(pattern, regex=True, na=False)
    count = has_pattern.sum()
    print(f"\n- {name}: {count} rows containing this pattern.")

    if count > 0:
        # Display 3 random examples if they exist
        examples = df_stacked[has_pattern]['text'].sample(min(3, count)).values
        print(f"  Examples of '{name}':")
        for example in examples:
            print(f"    - {example}")
    else:
        print(f"  No examples found for '{name}'.")

Pattern Analysis:

- URL: 0 rows containing this pattern.
  No examples found for 'URL'.

- HTML Tags: 4 rows containing this pattern.
  Examples of 'HTML Tags':
    - <<creepy loui face.jpg>>
    - If by "better", you mean "more fun", then I'd go with the second one. <smile>
    - Yes, definitely classy. <rolls eyes>

- Extra Whitespace: 451370 rows containing this pattern.
  Examples of 'Extra Whitespace':
    - i feel pretty virtuous about that
    - i want u to know tt its ok to feel burdened to feel sad to feel all tt u are feeling
    - i have also been working on the house i am trying to sell which i often feel is robbing me of the precious time i have away from work

- Special Characters: 52362 rows containing this pattern.
  Examples of 'Special Characters':
    - Okaaaay? I'm not sure how to respond to that, no offense.
    - after that we had no sustained damage for the fight so [NAME] and [NAME] just killed [NAME]
    - As sure as gods got sandals, it sure beats fighting dudes with treasure trails

### Text Data Cleaning Patterns
Common issues in text datasets include:
1. **HTML Tags**: Leftover tags from web scraping.
2. **Special Characters/Emojis**: Non-ASCII characters that might confuse models.
3. **Numbers**: Often removed if not relevant to the sentiment.
4. **Extra Whitespace**: Multiple spaces, tabs, or newlines.
5. **Punctuation**: Often normalized or removed.

# Preprocessing

1. Not convert all to lower case as it matters like if the person was talking in captial letters most likely he is angry so it might be helpful

2. Keeping the special characters as its as its also may be useful

3. Convert Emojis using `Demojize` library to translate them into text

4. Removing Stop words (i don't think they are important in this task)

### Cleaning Text: Converting Emojis and Removing Stop Words

Based on your requirements, I will now implement the following text cleaning steps:

1.  **Convert Emojis to Text**: Using the `demoji` library, emojis will be translated into their textual descriptions.
2.  **Remove Stop Words**: Common English stop words (e.g., 'the', 'is', 'a') will be removed, as they often do not contribute significant meaning to sentiment analysis.

In [ ]:
# Install necessary libraries
!pip install demoji nltk

Collecting demoji
  Downloading demoji-2.0.0-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Downloading demoji-2.0.0-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.4/43.4 kB 2.3 MB/s eta 0:00:00
Installing collected packages: demoji
Successfully installed demoji-2.0.0

In [ ]:
import demoji
import nltk
from nltk.corpus import stopwords

# Download stopwords if not already downloaded
try:
    stopwords.words('english')
except LookupError:
    nltk.download('stopwords')

# Helper function to format emoji descriptions for demoji.replace
def format_emoji_description_for_replace(match):
    # The 'match' object is an re.Match object, we need to extract the string
    emoji_str = match.group(0)
    # demoji.findall(emoji_str) returns a dictionary like {'👋': 'waving hand'}
    descriptions = demoji.findall(emoji_str)
    # Check if a description was found for the current emoji_char
    if emoji_str in descriptions:
        return f"<{descriptions[emoji_str]}>"
    return emoji_str # Fallback: return original emoji if no description is found

# Function to convert emojis to text
def convert_emojis(text):
    # Pass the helper function as the second positional argument to demoji.replace
    return demoji.replace(text, format_emoji_description_for_replace)

In [ ]:
# Function to remove English stop words
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return " ".join(filtered_words)

In [ ]:
# Apply emoji conversion and stop word removal
df_stacked['text_cleaned'] = df_stacked['text'].apply(convert_emojis)
df_stacked['text_cleaned'] = df_stacked['text_cleaned'].apply(remove_stopwords)

print("Original vs. Cleaned Text Examples:")
# Display some examples
display(df_stacked[['text', 'text_cleaned']].sample(5))

Original vs. Cleaned Text Examples:

,text,text_cleaned
800,/* Consciousness Level */ The Other is confuse...,/* Consciousness Level */ confused dumb <-- evil
403769,i wonder if i am the only one who feels like i...,wonder one feels like deceived complacency enr...
48883,Wowza...you hit the roommate jackpot huh? She ...,Wowza...you hit roommate jackpot huh? sounds u...
236927,i feel terrible and i feel terrible all over,feel terrible feel terrible
239241,i feel that i have also become more appreciati...,feel also become appreciative life

In [ ]:
display(df_stacked[['text', 'text_cleaned']].sample(5))

,text,text_cleaned
162677,i feel groggy and want to sleep for hours more,feel groggy want sleep hours
233229,i feel some trepidation looking over a blank c...,feel trepidation looking blank calendar consid...
235503,i feel stupid ineffectual impotent,feel stupid ineffectual impotent
435185,im off the booze for a month as well so am fee...,im booze month well feeling irrationally virtu...
205854,i feel most afraid or nervous such days are no...,feel afraid nervous days infrequent brief exer...

In [ ]:
df_stacked.shape

(451552, 30)

In [ ]:
# Save the cleaned DataFrame to a CSV file
df_stacked.to_csv('cleaned_emotions_data.csv', index=False)
print("DataFrame saved to 'cleaned_emotions_data.csv'")

DataFrame saved to 'cleaned_emotions_data.csv'